### ISSUE TITLE
Log error class

### ISSUE THREAD

**Issue by sagitt** [MrSleeps/Juwel-HeliaLux-Home-Assistant-Custom-Component#1]
Hi, very good work! i love this

I'm using the last HA version 2022.02.5 and see this in logs:

Logger: homeassistant.helpers.entity
Source: helpers/entity.py:580
First occurred: 11:21:40 (5 occurrences)
Last logged: 11:21:41

Entity sensor.aquariumled_current_profile (<class 'custom_components.juwel_helialux.sensor.JuwelSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.aquariumled_white (<class 'custom_components.juwel_helialux.sensor.JuwelSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.aquariumled_blue (<class 'custom_components.juwel_helialux.sensor.JuwelSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.aquariumled_red (<class 'custom_components.juwel_helialux.sensor.JuwelSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.aquariumled_green (<class 'custom_components.juwel_helialux.sensor.JuwelSensor'>) implements device_state_attributes. Please report it to the custom component author.

**Comment by MrSleeps** [comment]
The latest version should have fixed that :)
