### ISSUE TITLE
[Request] Controll lights via HASS

### ISSUE THREAD

**Issue by freakadings** [MrSleeps/Juwel-HeliaLux-Home-Assistant-Custom-Component#2]
Today i recieved my lamp and controller and was amazed, that there's already a plugin for home assistant to read the values. So thank you very much for your work!
Would it also be possible to implement the way back to controll the lamps and cloudyness and set profiles? 
I think it would be great for simulating ramdom day-types :)

All the best,
Merlin

**Comment by MrSleeps** [comment]
Bit beyond my python skills at the moment, but it is on the cards!

**Comment by MrSleeps** [comment]
You can now do this with the latest version!

**Comment by freakadings** [comment]
Nice! I'm updating right away.
Thank you very much for your work :)
