### ISSUE TITLE
Something broke: 'brightness'

### ISSUE THREAD

**Issue by CrasyHarry** [MrSleeps/Juwel-HeliaLux-Home-Assistant-Custom-Component#4]
I have a issue. 
This is the log:

Logger: custom_components.juwel_helialux.sensor
Source: custom_components/juwel_helialux/sensor.py:117
Integration: juwel_helialux (documentation, issues)
First occurred: 10:12:22 (18 occurrences)
Last logged: 10:46:23

Something broke: 'brightness'

I'm new in HA.. i need some help . Please.

**Comment by CrasyHarry** [comment]
????????????

**Comment by dMopp** [comment]
Project seems to be dead  :(. Same issue here

**Comment by MrSleeps** [comment]
Sorry, I no longer use home assistant.

Just reinstalled HA on a vm and I can't replicate the error, works out of the box for me

**Comment by dMopp** [comment]
This is a random thing, works for days or stop working after few hours, i cant tell you why, too.

Anyway i found a solution for myself:

`  - platform: command_line
    name: Helialux Profile
    unique_id: helialux_profile
    command: curl http://192.168.99.197/statusvars.js | awk -F \; '{print $6}' | cut -d '=' -f2 | sed "s@'@@g"

  - platform: command_line
    name: Helialux White
    unique_id: helialux_white
    unit_of_measurement: "%"
    command: curl http://192.168.99.197/statusvars.js | awk -F \; '{print $10}' | cut -d '=' -f2 | cut -d ',' -f1 | sed "s@\[@@g" | sed "s@\]@@g"
  
  - platform: command_line
    name: Helialux Red
    unique_id: helialux_red
    unit_of_measurement: "%"
    command: curl http://192.168.99.197/statusvars.js | awk -F \; '{print $10}' | cut -d '=' -f2 | cut -d ',' -f4 | sed "s@\[@@g" | sed "s@\]@@g"
  
  - platform: command_line
    name: Helialux Green
    unique_id: helialux_green
    unit_of_measurement: "%"
    command: curl http://192.168.99.197/statusvars.js | awk -F \; '{print $10}' | cut -d '=' -f2 | cut -d ',' -f3 | sed "s@\[@@g" | sed "s@\]@@g"
  
  - platform: command_line
    name: Helialux Blue
    unique_id: helialux_blue
    unit_of_measurement: "%"
    command: curl http://192.168.99.197/statusvars.js | awk -F \; '{print $10}' | cut -d '=' -f2 | cut -d ',' -f2 | sed "s@\[@@g" | sed "s@\]@@g"`

Its dirty bash/curl mix but works fine for me and because i only what to read its totally enough

**Comment by MrSleeps** [comment]
Have pushed an update, should be available in HACS shortly.. I think the error might be down to timeouts/offline (again, couldn't replicate anything). 

Feel free to give it a try and open a new issue if the problem still exists.

I'll be reinstalling HA at some point so I should be able to debug things easier.. Moving house sucks.

**Comment by jakerol** [comment]
I had this issue all the time and no data. Noticed that I had firmware 1.0 in Helialux smart control. When I updated the firmware to the latest (ver 2.2.2) it all started to work.

**Comment by MrSleeps** [comment]
Ahh that's interesting, thanks for that info.. Mine is v2.1, the information it provides is probably different between v1 and v2..

I'll add that to the readme :)

**Comment by beckerj** [comment]
Version 2 is a complete overhaul of the software, version 1 was a nightmare.
This german site as a nice overview about what changed: 
https://www.abenteuer-aquarium.de/alles-besser-in-2-0-neue-firmware-wertet-den-helialux-smartcontrol-ordentlich-auf/
Google Translate english version:
https://www-abenteuer--aquarium-de.translate.goog/alles-besser-in-2-0-neue-firmware-wertet-den-helialux-smartcontrol-ordentlich-auf/?_x_tr_sl=de&_x_tr_tl=en&_x_tr_hl=de&_x_tr_pto=wapp
